izumin5210/OHP

package.json, src/components/preview/Page.js, src/components/preview/SlidePreview.js, src/containers/PreviewContainer.js, src/containers/SlideContainer.js, src/store/selectors/processor.js, src/utils/remark-extract-styles/index.js, yarn.lock
[![https://gyazo.com/7cb1a29179111275d037115e5c2e6b05](https://i.gyazo.com/7cb1a29179111275d037115e5c2e6b05.gif)](https://gyazo.com/7cb1a29179111275d037115e5c2e6b05)
=> Support <style> tag

src/containers/EditorContainer.js
https://github.com/izumin5210/OHP/projects/1#card-2831144
=> Debounce user input

src/components/preview/Page.js, src/containers/SlideContainer.js, src/store/selectors/processor.js, src/utils/remark-newpage-directive/NewpageDirectiveVisitor.js, src/utils/remark-newpage-directive/index.js, src/utils/remark-newpage-directive/types.js, src/utils/remark-page-props-directive/index.js
https://github.com/izumin5210/OHP/projects/1#card-2825406
=> <!-- page className='custom-page-class' -->

decls/react-measure.js, package.json, src/components/preview/SlidePreview.js, src/containers/EditorContainer.js, src/containers/PreviewContainer.js, src/containers/SlideContainer.js, src/entities/Page.js, src/store/modules/editorState.js, src/store/modules/entities/index.js, src/store/modules/entities/pages.js, src/store/modules/index.js, src/store/modules/previewState.js, src/store/selectors/editorState.js, src/store/selectors/entities/pages.js, src/store/selectors/pages.js, src/store/selectors/processor.js, src/types/index.js, src/utils/random.js, src/utils/remark-newpage-directive/NewpageDirectiveVisitor.js, src/utils/remark-newpage-directive/types.js, test/store/selectors/entities/pages.js, yarn.lock
-  scroll to current page in preview
-  highlight current page in preview (optional)
-  highlight range of current page in editor (optional)
=> Prepare sync scroll

package.json, src/components/preview/SlidePreview.js, src/containers/PreviewContainer.js, src/store/selectors/entities/pages.js, src/store/selectors/pages.js, src/store/selectors/preview.js, test/store/selectors/entities/pages.js, yarn.lock
[![https://gyazo.com/1dd6b154eaf2698fe635fcbd7df0f2f0](https://i.gyazo.com/1dd6b154eaf2698fe635fcbd7df0f2f0.gif)](https://gyazo.com/1dd6b154eaf2698fe635fcbd7df0f2f0)
=> Make scroll slide preview in sync with cursor position in editor

src/components/editor/Editor.js, src/containers/EditorContainer.js, src/main/MainMenu.js, src/main/constants.js, src/main/index.js, src/services/ipc.js, src/services/preferences.js, src/settings/ipc.js, src/settings/localStorage.js, src/store/modules/editor.js, src/store/sagas/editor.js, src/store/sagas/index.js, src/store/sagas/ipc.js, src/store/selectors/editor.js, src/types/index.js
=> Keymap switcher

src/main/MainMenu.js, src/main/index.js, src/main/windows/Window.js
=> Handle quit on darwin

decls/unist-util-visit-children.js, decls/unist-util-visit.js, package.json, src/components/outline/Link.js, src/components/outline/List.js, src/components/outline/ListItem.js, src/components/outline/Outline.js, src/components/outline/Wrapper.js, src/components/outline/index.js, src/entries/index.css, src/services/DocumentProcessor.js, src/settings/colors.js, src/settings/processor.js, src/utils/remark-list-depth/index.js, yarn.lock
To close #62 
[![https://gyazo.com/c1b341069cdfb78af5880edf3c0a00f4](https://i.gyazo.com/c1b341069cdfb78af5880edf3c0a00f4.png)](https://gyazo.com/c1b341069cdfb78af5880edf3c0a00f4)
=> Apply styles to outline pane

src/components/editor/Editor.js
=> Make clear undo history when other document is opened

.babelrc, package.json, yarn.lock
To resolve paths in main process...
=> Introduce babel-plugin-module-resolver

decls/electron.js, src/entries/app.js, src/main/index.js, src/main/services/DocumentWriter.js, src/main/services/dialog.js, src/main/setup.js, src/main/windows/MainWindow.js, src/main/windows/Window.js, src/main/windows/WindowManager.js, src/main/windows/index.js
=> Support multi window and to create new fine

src/components/common/CirclesLoader.js, src/components/preview/Container.js, src/settings/colors.js, src/store/modules/preview.js, src/store/sagas/preview.js, src/store/selectors/preview.js, src/types/index.js
[![https://gyazo.com/96b0bcc2dd8b082f47b6f3096976ef33](https://i.gyazo.com/96b0bcc2dd8b082f47b6f3096976ef33.gif)](https://gyazo.com/96b0bcc2dd8b082f47b6f3096976ef33)
=> Show loader when documents are processed

src/entries/app.js, src/index.html, src/main/windows/Window.js
=> Show loading animation until starting application

packages/processor/package.json, packages/processor/src/__tests__/__snapshots__/Processor.test.js.snap, packages/remark-insert-page-number/package.json, packages/remark-insert-page-number/src/__test__/fixtures/normal/output.html, packages/remark-insert-page-number/src/plugin.js, packages/remark-page-number-directive/package.json
=> Disable page numbers in default

packages/@ohp/app/package.json, yarn.lock
=> Downgrade react-measure to 1.4.7

flow-typed/react-measure.js, packages/@ohp/app/package.json, packages/@ohp/app/src/components/preview/Container.js, packages/@ohp/app/yarn.lock
=> react-measure 2.x

README.md, package.json, packages/@ohp/app/package.json, packages/@ohp/app/yarn.lock, packages/remark-insert-page-number/package-lock.json, packages/remark-page-number-directive/package-lock.json, yarn.lock
=> Add utility scripts

packages/@ohp/app/src/store/sagas/exportAsPdf.js
=> Fix crash bug

packages/@ohp/app/src/store/sagas/preview.js, packages/@ohp/processor/package-lock.json, packages/@ohp/processor/package.json, packages/@ohp/processor/src/Processor.js, packages/@ohp/processor/src/errors.js, packages/@ohp/processor/src/index.js
=> Catch processor errors

packages/@ohp/app/src/components/page/ExternalLink.js, packages/@ohp/app/src/components/page/index.js, packages/@ohp/app/src/main/windows/Window.js, packages/@ohp/app/src/settings/processor.js
=> Suppress opening external links in the application window
